import { Plant } from '../interfaces/plant.interface';

export const plants: Plant[] = [
  {
    id: 1,
    name: 'Monstera Deliciosa',
    desctiption: 'Lorem ipsum',
    image: 'https://source.unsplash.com/random/500x500?monstera',
    hydroponics: true,
    difficulty: 1,
    light: 'light',
    water: 'water',
    dew: true,
    propagation: 'propagation',
    common_problems: 'common_problems',
    slug: 'monstera'
  },
  {
    id: 2,
    name: 'Alocasia wentii',
    desctiption: 'Lorem ipsum',
    image: 'https://source.unsplash.com/random/500x500?alocasia',
    hydroponics: true,
    difficulty: 1,
    light: 'd',
    water: 'd',
    dew: true,
    propagation: 'x',
    common_problems: 'd',
    slug: 'alocasia-wentii'
  },
  {
    id: 3,
    name: 'Philodendron scandens',
    desctiption: 'Lorem ipsum',
    image: 'https://source.unsplash.com/random/500x500?philodendron',
    hydroponics: true,
    difficulty: 1,
    light: 'd',
    water: 'd',
    dew: true,
    propagation: 'x',
    common_problems: 'd',
    slug: 'philodendron-scandens'
  },
  {
    id: 4,
    name: 'Epipremnum Golden',
    desctiption: 'Lorem ipsum',
    image: 'https://source.unsplash.com/random/500x500?epipremnum',
    hydroponics: true,
    difficulty: 1,
    light: 'd',
    water: 'd',
    dew: true,
    propagation: 'x',
    common_problems: 'd',
    slug: 'epipremnum-golden'
  },
  {
    id: 5,
    name: 'Scindapsus pictus Exotica',
    desctiption: 'Lorem ipsum',
    image: 'https://source.unsplash.com/random/500x500?scindapsus',
    hydroponics: true,
    difficulty: 1,
    light: 'd',
    water: 'd',
    dew: true,
    propagation: 'x',
    common_problems: 'd',
    slug: 'scindapsus-pictus-exotica'
  },
  {
    id: 6,
    name: 'Syngonium Pixie',
    desctiption: 'Lorem ipsum',
    image: 'https://source.unsplash.com/random/500x500?syngonium',
    hydroponics: true,
    difficulty: 1,
    light: 'd',
    water: 'd',
    dew: true,
    propagation: 'x',
    common_problems: 'd',
    slug: 'syngonium-pixie'
  },
  {
    id: 7,
    name: 'Zamioculcas zamiifolia',
    desctiption: 'Lorem ipsum',
    image: 'https://source.unsplash.com/random/500x500?zamioculcas',
    hydroponics: true,
    difficulty: 1,
    light: 'd',
    water: 'd',
    dew: true,
    propagation: 'x',
    common_problems: 'd',
    slug: 'zamioculcas-zamiifolia'
  },
  {
    id: 8,
    name: 'Calathea orbifolia',
    desctiption: 'Lorem ipsum',
    image: 'https://source.unsplash.com/random/500x500?calathea',
    hydroponics: true,
    difficulty: 1,
    light: 'd',
    water: 'd',
    dew: true,
    propagation: 'x',
    common_problems: 'd',
    slug: 'calathea-orbifolia'
  },
  {
    id: 9,
    name: 'Marantha leuconeura Fascinator',
    desctiption: 'Lorem ipsum',
    image: 'https://source.unsplash.com/random/500x500?marantha',
    hydroponics: true,
    difficulty: 1,
    light: 'd',
    water: 'd',
    dew: true,
    propagation: 'x',
    common_problems: 'd',
    slug: 'marantha-leuconeura-fascinator'
  }
];
